openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error
    SearchCharacterResponse:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del personaje
        altura:
          type: string
          description: Altura del personaje
        masa:
          type: string
          description: Peso del personaje
        consejo:
          type: string
          description: Consejo del personaje
        color_de_cabello:
          type: string
          description: Color de cabello del personaje
        color_de_ojos:
          type: string
          description: Color de ojos del personaje
        color_de_piel:
          type: string
          description: Color de piel del personaje
        anio_de_nacimiento:
          type: string
          description: Año de nacimiento del personaje
        genero:
          type: string
          description: Genero del personaje
  securitySchemes: {}
info:
  title: Obtener personaje de Star Wars y un consejo suyo
  description: Obtener personajes de Star Wars y un consejo suyo
  version: 1.0.0
paths:
  '/fusionados/{id}':
    get:
      operationId: retrieveMergedData
      summary: Obtener personaje de Star Wars y un consejo suyo
      description: Obtener personajes de Star Wars y un consejo suyo
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCharacterResponse'
        '401':
          description: No autorizado - API key inválida o faltante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Acceso prohibido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit excedido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
