service: save-custom-information-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-2
  memorySize: 128
  timeout: 15
  architecture: arm64
  logRetentionInDays: 3
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    CUSTOM_TABLE_NAME: ${ssm:/challengue-rimac/dynamodb/custom_data_table_name}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: ${ssm:/challengue-rimac/dynamodb/custom_data_table_arn}

functions:
  saveInformation:
    handler: src/handler.handler
    events:
      - http:
          path: /almacenar
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    target: 'node20'
    platform: 'node'
    sourcemap: true
    sourcesContent: false
    external:
      - '@aws-sdk/*'
  prune:
    automatic: true
    number: 1

package:
  individually: true
  patterns:
    - '!**'
    - 'src/**'
    - 'node_modules/**'
